{% set version = "0.6.1" %}

package:
  name: otpod
  version: {{ version }}

source:
  fn: otpod-{{ version }}.tar.gz
  url: https://github.com/openturns/otpod/archive/v{{ version }}.tar.gz
  sha256: 73c0cb0b0948199de03dc43d426a6a1cb58dfd68335fe963213902e61f05cab1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - setuptools
    - python
    - openturns
  run:
    - python
    - openturns
    - matplotlib >=1.5
    - scikit-learn >=0.17
    - statsmodels >=0.6
    - decorator >=4.0

test:
  source_files:
    - test/
    - doc/
  requires:
    - pytest
    - nbformat
    - nbconvert
  commands:
    - py.test test/  # [not osx]
  imports:
    - otpod

about:
  home: http://openturns.org/
  license_family: LGPL
  license: LGPL3
  license_file: COPYING.LESSER
  summary: A module to build Probability of Detection for Non Destructive Testing

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
