{% set version = "0.6.7" %}

package:
  name: otpod
  version: {{ version }}

source:
  fn: otpod-{{ version }}.tar.gz
  url: https://github.com/openturns/otpod/archive/v{{ version }}.tar.gz
  sha256: 9eb0f900d8787186c2be197d839f9428990abfa05ff888fdb5f564ee9feb8907

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - setuptools
    - python >=3
    - openturns >=1.16
  run:
    - python >=3
    - openturns >=1.16
    - matplotlib-base >=1.5
    - scikit-learn >=0.17
    - statsmodels >=0.6
    - decorator >=4.0

test:
  source_files:
    - test/
    - doc/
  requires:
    - pytest
    - nbformat
    - nbconvert
  commands:
    - py.test test/  # [not osx]
  imports:
    - otpod

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: A module to build Probability of Detection for Non Destructive Testing

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
