{% set version = "0.6.11" %}

package:
  name: otpod
  version: {{ version }}

source:
  fn: otpod-{{ version }}.tar.gz
  url: https://github.com/openturns/otpod/archive/v{{ version }}.tar.gz
  sha256: bdcc5c33e5d0eae2b25705a67bbe7affe5842edcf43c38f0197ed7aa3fa8741a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - openturns >=1.18
  run:
    - python >={{ python_min }}
    - openturns >=1.18
    - matplotlib-base >=1.5
    - scikit-learn >=0.17
    - statsmodels >=0.6
    - decorator >=4.0


test:
  source_files:
    - test/
    - doc/
  requires:
    - pytest
    - nbformat
    - nbconvert
    - python {{ python_min }}
  commands:
    - py.test test/  # [not osx]
  imports:
    - otpod

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: A module to build Probability of Detection for Non Destructive Testing

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
