{% set version = "0.4" %}

package:
  name: otpod
  version: {{ version }}

source:
  fn: otpod-{{ version }}.tar.gz
  url: https://github.com/openturns/otpod/archive/v{{ version }}.tar.gz
  sha256: d051a48227e7d387cb3cdd6c6368c5173b85e6ac08e82291316637266f63863b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - python
    - openturns
    - matplotlib >=1.5
    - scikit-learn >=0.17
    - statsmodels >=0.6
    - decorator >=4.0

test:
  source_files:
    - test/
    - doc/
  requires:
    - pytest
    - nbformat
    - nbconvert
  commands:
    - py.test test/  # [not osx]
  imports:
    - otpod

about:
  home: http://openturns.org/
  license_family: LGPL
  license: LGPL3
  license_file: COPYING.LESSER
  summary: A module to build Probability of Detection for Non Destructive Testing

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
