travis:
  secure:
    BINSTAR_TOKEN: P2KuPupSyxjIoYP7q4/15bR54w57WA2X5Km8FU1wlv5fj+VIbAHhy5un6mJGC5xtBjf6paSf6wud3CajZkMjXrBUwK1FTI50seCxF4sdD0t63n5Kvl913bJAUzBx2jhEqdyCKGJBiwRMkj8M6XeSpG0vig0Mi1YQCxnDoleWb487qXrYodkc6UkjjV4LKXpzW7pG7ybfTKA9OWskcEfXoek77U9W+Uvm2QNCX/gd4ntiIUhwyn/RU2XyPQQeAdGmK8K1kZ1Hbc5xEO3VqU8k312Ku6nIEvHd6HjJMT/Si2Stqe4U97MniEygvxncHan/mP56SxyH2T+VMu7mYM16nz6BwJ0jY/Mn2ekAF7VF5CNVg+p2JnAPdl0O430jl8BlBorhCtl0QKesqbZ0E+w0QmUlV5MfGTWjepZ3OPrvfhZovbcUaY9xiGwThzRBDutU6t/iwP24iFM5sg+hBmW6GrBKljuuZrlcaTkhem1+QYPYNNUwtRIGG/hvdvqp+ezSfsOBakZE/X7r7xAKIMazhitP+4OcJE9EtlowOfoognEoajzCfPMzNoo8OSh3L71iN3tMaY9VLA+IA95NsIELVAVQY2O0JbAdzSgqUeB9UAiIT5iFzDVN4agO90Vl0x7ywEQq1rU2fKhCOJtuDDvJ2k8IB0k19QqEGniOPGPjC0U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
