travis:
  secure:
    BINSTAR_TOKEN: JGPpyV1Rw8vF984uazu9U4ZUUoWF8pFcLlIwV7jvhuC8EzRwME5+eQbO8S1Bk/fkdaysP5kEDJFbnIw2cgb+uaskmeS3GggMABG7YccZlxeC4f/rPKo4KA6PVx1UeoE4qN7fpQG+NacM29yID2CRzUN+hg89aaV9qADgYEqwQoURftZU9AIGwcugalSn01ej2F3DpT/LN8HcOJFBIYndl8Cn/IrxFu1GTaWKOc7oLfA9eQrXRJbmR9kpsV9u6elVxZIuGgRvIwN5tg08QxcmvDCZkSXnO2Ql70udLF8xPeKPxfJEc3WSAkZ2dutnkhN3F36Q+Eiz7Jwos/4TXKz4/nDvMrgUnkeUq7IXiC08skylrVGgz3rlmtSaT2jD99MJJ2iGJ+nHTuTT+nLDDhhbDuL5I4qXXUkAU/HicUpNpR561lIjjuOsl0fqxwG1Uox7zj596VB6IrwTauxtbweZ9OMOuXYU3HcsLhVm5WoWYzyJAkr7vWi5qwnpo3fPUjGAxBjdVJxspQ0lQxTFgh0EzP82rolxX7mrvVxTSCDEDCyZRa52TBoFlFjuNZWI7kyVHzySGpkIIuRI2ShUXo7D21u+WPqFBuY91/V0LQcaVjOonazRu5J/998EFceceJ/o9qBVLQJdVIR4A3ssRIpNyXNAU7MDWa48tWz7LAPD9sk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
