travis:
  secure:
    BINSTAR_TOKEN: NRER7HYOslHmIVPQ6D4NLnX6v2bGrf9OejsJKeX3GjtS6uos9vpL0beXxYZpgfnIXcczdOI8bDxQZaMM8yYGnigozX+oOS8RHpdy2FQrLWzmKN1mFk63LX9euQuzW98Fk0B2Qeiup2F2fAv+fPzoBJbbg4WjcsXlxGSMCqHBZZ/pubVoVwuMvY01O4V5T/8qBQzt9Mu1sUmuyZ4kIOy4JIpuPaPasVigBszvNI/eRhBAlmHya7rJUqDBLrD2wC+aKqlTaFwSaxZh/+sd9j3itdfMQYumWNyeJWszy1mWoA/ocZJ10NWLKjppdN5QI+IVkKFNwjGrvGV37SFxI30v/GsGsUNw9Xiw0gNS0PNMUYLwDEDknlfgahG1wM00O9fwBXmCnFnOmACdvyT6dc6n5yVXBQMIsAiptLtZnTl+9kVAwYQdFyAKjzyj4dDo1aza3X8J0ih5P0Nn8t2HcuxGw6nfjMbPXbKp+bEY9q2yLS3+v3XtodRH+HWlkKilgy001QLCb6zPvJxG3RfKD+neyOVmH7wKU24BeVaJkw7EAkK/4Rvo9YVLKx93j8nCMG9Loo6wR/7uZLE99XcthaASB+LOrCnR5OTiXOiWfnLbAxDJ35A9galEWHhFVFg07mbLI+eY/ETbZCkNrzSZAaak0C9OiTVxsPo7k+CauKIglSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
